### ISSUE TITLE
VCF Rotate credentials fails in prevalidation with error "Entity name 10.0.0.30 not found" when using resource IP

### ISSUE THREAD

**Issue by cmsriram** [vmware/terraform-provider-vcf#139] opened 2024-03-05 09:09 UTC
### Code of Conduct

- [X] I have read and agree to the [Code of Conduct](https://github.com/vmware/terraform-provider-vcf/blob/main/CODE_OF_CONDUCT.md).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

1.7

### Terraform Provider

VCF provider

### VMware Cloud Foundation

5.1

### Description

Testing the 'vcf_credentials_rotate' its found that it works only when using the resource FQDN but not the IP address. Tested this on both the nsxt manager and the vCenter and it throws the below error in prevalidation of the task :

Description	Prevalidation of password rotate request
Progress Messages	Entity name 10.0.0.30 not found.
Error

Message: Entity name 10.0.0.30 not found.
Remediation Message: Use a valid entity name.

### Affected Resources or Data Sources

vCenter and the NSXT managers 

### Terraform Configuration

Attaching the word doc with the code for main.tf and variables.tf files.
[VCF-Credentials-Rotate.docx](https://github.com/vmware/terraform-provider-vcf/files/14492934/VCF-Credentials-Rotate.docx)

### Debug Output

Description	Prevalidation of password rotate request
Progress Messages	Entity name 10.0.0.30 not found.
Error

Message: Entity name 10.0.0.30 not found.
Remediation Message: Use a valid entity name.

Reference Token: SMJN21

Cause: Entity name 10.0.0.30 not found.

### Expected Behavior

The vcf_credentials_rotate task should work with resource IP's.

### Actual Behavior

Its observed that the task fails in VCF with the below errors :

Description	Prevalidation of password rotate request
Progress Messages	Entity name 10.0.0.30 not found.
Error

Message: Entity name 10.0.0.30 not found.
Remediation Message: Use a valid entity name.

Reference Token: SMJN21

### Steps to Reproduce

1. Execute the 'vcf_credentials_rotate' resource with 'resource_name' field being set to the IP address of the resource instead of FQDN.
2. Its observed that the task fails in VCF with the below errors :

Description	Prevalidation of password rotate request
Progress Messages	Entity name 10.0.0.30 not found.
Error

Message: Entity name 10.0.0.30 not found.
Remediation Message: Use a valid entity name.

Reference Token: SMJN21

**Comment by stoyanzhelyazkov** [comment] 2024-03-05 09:37
The terraform resource does not do any validation on the entity name. It just populates it in the specification and calls the VCF API to rotate the credentials.

@cmsriram did you observe an error in the SDDC manager? Or was it just a problem with "terraform apply"?

If the former was true it would be useful to share the logs from the SDDC manager.
I will close the issue for now since it does not seem to be caused by the provider.

**Closed by stoyanzhelyazkov** 2024-03-05 09:37 UTC
Labels: bug, needs-triage, pending-review

**Comment by cmsriram** [comment] 2024-03-08 10:47
@stoyanzhelyazkov I observed the issue in the SDDC manager with the task failing. That is how thought of tracking this issue here. Will repro and provide the logs.
